version: '3'
services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /mnt/efs/wordpress:/var/www/html
    restart: always
    ports:
      - 80:80
      - 8080:8080
    environment:
      WORDPRESS_DB_HOST: databasewp.cr0o8ky00uod.us-east-1.rds.amazonaws.com:3306
      WORDPRESS_DB_USER: teste
      WORDPRESS_DB_PASSWORD: teste123
      WORDPRESS_DB_NAME: databasewp
