version: '3.3'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_USER: teste
      MYSQL_PASSWORD: teste
      MYSQL_DATABASE: wordpress
    ports:
      - "3306:3306"
    networks:
      - sub-d
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - /efs/paulo-weinberger/var/www/html:/var/www/html
    environment:
      TZ: America/Sao_Paulo
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: teste
      WORDPRESS_DB_PASSWORD: teste
    networks:
      - sub-d

networks:
  sub-d:
    driver: bridge
